-- Quick fix: Disable RLS temporarily to test authentication
-- Run this in your Supabase SQL editor

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE freelancers DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE certifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE edit_logs DISABLE ROW LEVEL SECURITY;
